name: Manage CloudFormation Stack

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform: plan, apply, or destroy'
        required: true
        default: 'plan'
      stack_name:
        description: 'CloudFormation Stack Name'
        required: true
        default: 'tac-network-stack'
      template_file:
        description: 'Path to CloudFormation template'
        required: false
        default: 'network.yaml'

env:
  AWS_REGION: ap-northeast-1

jobs:
  manage:
    runs-on: ubuntu-latest
    environment: manual-approval
    env:
      STACK_NAME: ${{ github.event.inputs.stack_name || 'tac-network-stack' }}
      TEMPLATE_FILE: ${{ github.event.inputs.template_file || 'network.yaml' }}
      ACTION: ${{ github.event.inputs.action || (github.event_name == 'push' && 'apply') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Validate CloudFormation Template
        if: env.ACTION != 'destroy'
        run: |
          aws cloudformation validate-template \
            --template-body file://$TEMPLATE_FILE

      - name: Plan (Create Change Set)
        if: env.ACTION == 'plan'
        run: |
          CHANGE_SET_NAME="preview-$(date +%s)"
          aws cloudformation create-change-set \
            --stack-name $STACK_NAME \
            --template-body file://$TEMPLATE_FILE \
            --change-set-name $CHANGE_SET_NAME \
            --capabilities CAPABILITY_NAMED_IAM
          aws cloudformation wait change-set-create-complete \
            --stack-name $STACK_NAME \
            --change-set-name $CHANGE_SET_NAME
          aws cloudformation describe-change-set \
            --stack-name $STACK_NAME \
            --change-set-name $CHANGE_SET_NAME \
            --query "Changes[*].ResourceChange" \
            --output table

      - name: Apply (Deploy Stack)
        if: env.ACTION == 'apply'
        run: |
          aws cloudformation deploy \
            --template-file $TEMPLATE_FILE \
            --stack-name $STACK_NAME \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset

      - name: Destroy Stack
        if: env.ACTION == 'destroy'
        run: |
          aws cloudformation delete-stack \
            --stack-name $STACK_NAME
